name: workflow-update-actions

on:
  workflow_dispatch:
  schedule:
    # Automatically run every Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  workflow-update-actions:
    name: Workflow Update Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update Workflow Action Versions
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          committer_username: ${{ vars.GIT_USER }}
          committer_email: ${{ vars.GIT_EMAIL }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ignore: '["github/codeql-action/init@v2", "github/codeql-action/autobuild@v2", "github/codeql-action/analyze@v2", "dependency-check/Dependency-Check_Action@main", "actions/upload-artifact@master"]'
